import React from 'react';
import { colors, radius, font, inputStyle, btnSecondary, descStyle, labelStyle, pageContainer, settingsCard, cardTitle, settingRow, settingRowTop, settingRowLeft, settingRowRight, settingRowLabel, settingRowDesc, navGroupTitle, navItem, navItemActive, cardDivider, inputWide } from './settingsStyles';

export const productSettingsStyles = {
    overlay: {
        position: 'fixed' as const,
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: colors.overlay,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2000,
    },
    modal: {
        backgroundColor: colors.bgSecondary,
        width: '100vw',
        height: '100vh',
        display: 'flex',
        flexDirection: 'column' as const,
        color: colors.textSecondary,
        overflow: 'hidden',
    },
    header: {
        padding: '12px 24px',
        borderBottom: `1px solid ${colors.borderPrimary}`,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: colors.bgPrimary,
        flexShrink: 0,
    },
    // 左上角「← 系统设置」返回按钮：看似标题，hover 有反馈（hover 效果由
    // settings-back-title / settings-back-arrow 两个 class 在全局 CSS 实现，
    // 因为 React 内联 style 不支持 :hover 伪类）。
    backTitle: {
        margin: 0,
        fontSize: '1.05rem',
        color: colors.textPrimary,
        fontWeight: 600,
        background: 'none',
        border: 'none',
        cursor: 'pointer',
        padding: '6px 10px',
        borderRadius: radius.sm,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
        fontFamily: 'inherit',
    },
    backArrow: {
        color: colors.textTertiary,
        fontSize: '1rem',
        lineHeight: 1,
        transition: 'color 0.15s ease',
    },
    closeBtn: {
        background: 'none',
        border: 'none',
        color: colors.textSecondary,
        fontSize: '1.5rem',
        cursor: 'pointer',
        padding: '0',
        width: '32px',
        height: '32px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: radius.sm,
        ':hover': {
            backgroundColor: colors.bgHover,
        }
    },
    mainContent: {
        display: 'flex',
        flex: 1,
        overflow: 'hidden',
        minHeight: 0,
    },
    sidebar: {
        width: '280px',
        backgroundColor: colors.bgSecondary,
        borderRight: `1px solid ${colors.borderPrimary}`,
        display: 'flex',
        flexDirection: 'column' as const,
        padding: '16px 0',
        flexShrink: 0,
    },
    searchBox: {
        padding: '0 16px 16px',
    },
    searchInner: {
        position: 'relative' as const,
    },
    searchIcon: {
        position: 'absolute' as const,
        left: '12px',
        top: '50%',
        transform: 'translateY(-50%)',
        color: colors.textTertiary,
        fontSize: font.lg,
        pointerEvents: 'none' as const,
        display: 'flex',
    },
    searchInput: {
        width: '100%',
        padding: '8px 12px 8px 34px',
        backgroundColor: colors.bgHover,
        border: `1px solid ${colors.borderPrimary}`,
        borderRadius: radius.md,
        color: colors.textPrimary,
        fontSize: font.base,
        outline: 'none',
        boxSizing: 'border-box' as 'border-box',
        ':focus': {
            borderColor: colors.accent,
        }
    },
    nav: {
        flex: 1,
        overflowY: 'auto' as const,
        padding: '0 8px',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '18px',
    },
    navGroup: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '2px',
    },
    navIcon: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '18px',
        height: '18px',
        fontSize: '15px',
        flexShrink: 0,
    },
    navText: {
        flex: 1,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap' as const,
    },
    // 导航项右侧的更新提示红点，样式与设置按钮齿轮上的点一致
    navBadge: {
        position: 'absolute' as const,
        right: '12px',
        top: '50%',
        transform: 'translateY(-50%)',
        width: '8px',
        height: '8px',
        borderRadius: '50%',
        backgroundColor: colors.danger,
        border: '1px solid var(--bg-primary)',
        flexShrink: 0,
    },
    // tab 顶部状态横幅：左竖边框 + 浅底，醒目但不突兀
    attentionBanner: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '10px',
        padding: '10px 12px',
        borderRadius: radius.sm,
        backgroundColor: colors.bgPrimary,
        border: `1px solid ${colors.borderPrimary}`,
        borderLeft: '3px solid',
    },
    attentionText: {
        color: colors.textSecondary,
        fontSize: font.sm,
        lineHeight: 1.6,
        flex: 1,
    },
    noResults: {
        padding: '20px 12px',
        textAlign: 'center' as const,
        color: colors.textTertiary,
        fontSize: font.base,
    },
    contentArea: {
        flex: 1,
        overflowY: 'auto' as const,
        backgroundColor: 'var(--bg-settings-canvas)',
        minWidth: 0,
    },
    pageContent: {
        ...pageContainer,
    },
    settingsContent: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '24px',
    },
    settingsGroup: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '20px',
    },
    groupTitle: {
        fontSize: font.base,
        fontWeight: 600,
        color: colors.textSecondary,
        marginTop: '8px',
        marginBottom: '4px',
        paddingBottom: '6px',
        borderBottom: `1px solid ${colors.borderPrimary}`,
    },
    // Orca 风格：卡片容器
    card: {
        ...settingsCard,
    },
    cardTitle: {
        ...cardTitle,
    },
    cardDivider: {
        ...cardDivider,
    },
    // Orca 风格：两列设置行
    row: {
        ...settingRow,
    },
    rowTop: {
        ...settingRowTop,
    },
    rowLeft: {
        ...settingRowLeft,
    },
    rowRight: {
        ...settingRowRight,
    },
    rowLabel: {
        ...settingRowLabel,
    },
    rowDesc: {
        ...settingRowDesc,
    },
    inputWide: {
        ...inputWide,
    },

    settingItem: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '8px',
    },
    settingLabel: {
        ...labelStyle,
    },
    settingDescription: {
        ...descStyle,
        marginTop: '-4px',
    },
    input: {
        ...inputStyle,
    },
    fontSizeRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    fontPreviewList: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
        gap: '8px',
    },
    fontPreviewCard: {
        width: '100%',
        minHeight: '70px',
        padding: '10px 12px',
        border: `1px solid ${colors.borderPrimary}`,
        borderRadius: radius.md,
        backgroundColor: colors.bgSecondary,
        color: colors.textSecondary,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '8px',
        textAlign: 'left' as const,
        cursor: 'pointer',
        transition: 'border-color 160ms ease, background-color 160ms ease',
    },
    fontPreviewCardSelected: {
        border: `1px solid ${colors.accent}`,
        backgroundColor: 'var(--bg-active-soft)',
    },
    fontPreviewHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '12px',
    },
    fontPreviewName: {
        color: colors.textPrimary,
        fontSize: font.base,
        fontWeight: 600,
    },
    fontPreviewDescription: {
        color: colors.textTertiary,
        fontSize: font.sm,
        marginLeft: '10px',
    },
    fontSelectedIndicator: {
        width: '20px',
        height: '20px',
        borderRadius: '50%',
        backgroundColor: colors.accent,
        color: 'var(--text-on-accent)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    fontPreviewSample: {
        color: 'var(--text-secondary)',
        fontSize: '13px',
        lineHeight: 1.45,
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    themeChoiceRow: {
        display: 'flex',
        gap: '10px',
        flexWrap: 'wrap' as const,
        marginTop: '4px',
    },
    themeChoiceCard: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        minWidth: '130px',
        padding: '11px 18px',
        border: `1px solid ${colors.borderPrimary}`,
        borderRadius: radius.md,
        backgroundColor: colors.bgSecondary,
        color: colors.textSecondary,
        fontSize: font.base,
        fontWeight: 500,
        cursor: 'pointer',
        transition: 'border-color 160ms ease, background-color 160ms ease',
    },
    themeChoiceCardActive: {
        border: `1px solid ${colors.accent}`,
        backgroundColor: 'var(--bg-active-soft)',
        color: colors.textPrimary,
    },
    fontSizeButton: {
        width: '34px',
        height: '34px',
        border: `1px solid ${colors.borderPrimary}`,
        borderRadius: radius.sm,
        backgroundColor: colors.bgSecondary,
        color: colors.textPrimary,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
    },
    fontSizeInputWrap: {
        width: '92px',
        height: '34px',
        display: 'flex',
        alignItems: 'center',
        border: `1px solid ${colors.borderPrimary}`,
        borderRadius: radius.sm,
        backgroundColor: colors.bgSecondary,
        overflow: 'hidden',
    },
    fontSizeInput: {
        width: '58px',
        height: '100%',
        padding: '0 8px',
        border: 'none',
        outline: 'none',
        backgroundColor: 'transparent',
        color: colors.textPrimary,
        fontFamily: 'var(--font-mono)',
        fontSize: font.base,
        boxSizing: 'border-box' as const,
    },
    fontSizeUnit: {
        color: colors.textTertiary,
        fontSize: font.sm,
    },
    resetAppearanceButton: {
        height: '34px',
        padding: '0 12px',
        border: `1px solid ${colors.borderPrimary}`,
        borderRadius: radius.sm,
        backgroundColor: 'transparent',
        color: colors.textSecondary,
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        cursor: 'pointer',
        fontSize: font.base,
    },
    secondaryButton: {
        ...btnSecondary,
    },
    statusGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
        gap: '12px',
    },
    statusCard: {
        padding: '14px',
        borderRadius: radius.md,
        border: `1px solid ${colors.borderPrimary}`,
        backgroundColor: colors.bgSecondary,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '8px',
    },
    statusCardLabel: {
        fontSize: font.sm,
        color: colors.textTertiary,
    },
    statusCardValue: {
        fontSize: font.lg,
        color: colors.textPrimary,
        fontWeight: 600,
        wordBreak: 'break-word' as const,
    },
    footer: {
        padding: '16px 24px',
        borderTop: `1px solid ${colors.borderPrimary}`,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: colors.bgPrimary,
    },
    footerActions: {
        display: 'flex',
        gap: '12px',
    },
    statusMsg: {
        color: colors.success,
        fontSize: font.base,
    },
    saveBtn: {
        padding: '8px 20px',
        borderRadius: radius.sm,
        border: 'none',
        backgroundColor: colors.accent,
        color: 'var(--text-on-accent)',
        cursor: 'pointer',
        fontWeight: 500,
        fontSize: font.base,
        ':hover': {
            backgroundColor: 'var(--accent-hover)',
        }
    },
    cancelBtn: {
        padding: '8px 20px',
        borderRadius: radius.sm,
        border: `1px solid ${colors.borderPrimary}`,
        backgroundColor: 'transparent',
        color: colors.textSecondary,
        cursor: 'pointer',
        fontWeight: 500,
        fontSize: font.base,
        ':hover': {
            backgroundColor: colors.bgHover,
        }
    },
    // 关闭确认弹层：覆盖在设置页之上，zIndex 略高于设置页
    unsavedOverlay: {
        position: 'fixed' as const,
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: colors.overlay,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2100,
    },
    unsavedModal: {
        backgroundColor: colors.bgSecondary,
        borderRadius: radius.lg,
        padding: '24px',
        width: '420px',
        maxWidth: '90vw',
        boxShadow: '0 4px 12px var(--shadow)',
    },
    unsavedTitle: {
        color: colors.textPrimary,
        fontSize: font.base,
        fontWeight: 600,
        margin: '0 0 12px 0',
    },
    unsavedMessage: {
        color: colors.textSecondary,
        fontSize: font.base,
        margin: '0 0 20px 0',
    },
    unsavedActions: {
        display: 'flex',
        gap: '10px',
        justifyContent: 'flex-end',
    },
    discardBtn: {
        padding: '8px 16px',
        borderRadius: radius.sm,
        border: '1px solid var(--danger-border)',
        backgroundColor: 'var(--danger-bg-subtle)',
        color: colors.danger,
        cursor: 'pointer',
        fontWeight: 500,
        fontSize: font.base,
    },
};
