package servicecenter

const webHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OpsCopilot · 内网服务中心</title><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><header><a href="/">OpsCopilot <small>内网服务中心</small></a><nav><a href="/">产品与下载</a><a href="/help">使用帮助</a><a href="/feedback">反馈</a><a href="/admin">管理</a></nav></header><main id="app"></main><footer>连接 · 排查 · 沉淀 · 复用</footer></body></html>`
const webCSS = `:root{color-scheme:light;--ink:#172f35;--muted:#587178;--line:#d3dedc;--accent:#08675e}*{box-sizing:border-box}body{margin:0;background:#f5f7f3;color:var(--ink);font:16px/1.7 ui-sans-serif,"Microsoft YaHei",sans-serif}header{padding:24px 6vw;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}header>a{font-weight:750;font-size:23px}small{font-size:12px;color:var(--muted);font-weight:400}nav{display:flex;gap:24px}a{color:var(--accent);text-decoration:none}main{max-width:1100px;margin:60px auto;padding:0 24px;min-height:65vh}h1{font-size:44px;line-height:1.3;max-width:800px}h2{margin-top:32px}p{color:var(--muted)}section,.card{background:white;border:1px solid var(--line);padding:28px;margin:20px 0;border-radius:10px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px}.eyebrow{letter-spacing:3px;font-size:12px;text-transform:uppercase}button,input,textarea,select{font:inherit}input,textarea,select{display:block;width:100%;padding:10px;margin:8px 0 16px;background:white;border:1px solid var(--line);border-radius:5px}input[type=checkbox]{display:inline;width:auto}button{padding:10px 20px;background:var(--accent);color:white;border:0;border-radius:5px;cursor:pointer;margin:4px 8px 4px 0}button.secondary{background:#e1ebe6;color:var(--ink)}label{display:block}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:10px;border-bottom:1px solid var(--line)}.error{color:#a33627}footer{padding:24px 6vw;border-top:1px solid var(--line);color:var(--muted)}@media(max-width:650px){header{display:block}nav{flex-wrap:wrap;gap:14px;margin-top:12px}h1{font-size:32px}}`
const webJS = `
const app=document.getElementById('app');
const el=(tag,text,parent=app)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;parent.append(n);return n};
let token='';
async function api(path,options={}){const headers={...options.headers};if(path.startsWith('/api/admin/'))headers.Authorization='Bearer '+token;const r=await fetch(path,{...options,headers});if(!r.ok)throw Error('请求失败（'+r.status+'）');return r.json()}
const post=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function button(text,fn,parent=app){const b=el('button',text,parent);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){alert(e.message)}finally{b.disabled=false}};return b}
function field(parent,label,type='text'){const l=el('label',label,parent);const n=el(type==='textarea'?'textarea':'input',undefined,l);if(type!=='textarea')n.type=type;return n}
function showFeedback(f,parent){el('p','编号：'+f.id+' · '+f.status,parent);el('pre',f.content,parent);el('p','回复：'+(f.reply||'暂无回复'),parent)}
async function portal(){el('div','OPERATIONS / KNOWLEDGE LOOP').className='eyebrow';el('h1','让每次排查，成为下一次解决问题的起点。');el('p','OpsCopilot 将终端连接、AI 辅助排查、快捷命令与团队知识放到同一个工作台。');const grid=el('div');grid.className='grid';for(const [t,d] of [['快速连接','SSH / Telnet 连接与终端工作台'],['辅助排查','结合运维知识定位问题，由人工确认执行'],['知识复用','共享知识与连接信息独立管理']]){const c=el('section',undefined,grid);el('h2',t,c);el('p',d,c)}el('h2','下载与更新日志');try{const rs=await api('/api/v1/releases');if(!rs.length)el('p','安装包正在同步，请稍后查看。');for(const r of rs){const c=el('section');el('h2',r.tag_name,c);for(const a of r.assets){const link=el('a',a.name+' ('+Math.round(a.size/1024/1024)+' MB)',c);link.href=a.browser_download_url;el('br',undefined,c)}el('pre',r.body,c)}}catch{el('p','暂时无法获取下载列表。')}}
function help(){el('h1','开始使用 OpsCopilot');for(const [t,d] of [['1. 安装与连接','从产品页下载安装包，解压到可写目录。创建 SSH 或 Telnet 连接，填写自己的连接凭据。'],['2. 使用工作台','Ctrl+K 可用自然语言生成 Linux 命令；先检查命令，再发送到终端。快捷命令可保存常用操作。'],['3. 团队共享','共享知识库与共享连接信息在各自设置中管理，与运营数据上报开关独立。'],['更新访问失败','在设置 → 内网服务中确认服务地址和网络连接；使用 HTTPS 时检查证书。旧客户端需手工安装一次支持内网服务的版本。'],['隐私与反馈','首次启动明确说明桌面与 CLI 的每日计数范围，用户可同意或拒绝；拒绝后可另行接受仅活跃与版本的最简方案，也可完全不上报。设置中可随时修改。不收集操作内容、文件路径或服务器信息，数据仅发送至内网服务器。共享知识库和共享连接独立管理。反馈由你主动填写并确认发送，不自动附带客户端日志。']]){const s=el('section');el('h2',t,s);el('p',d,s)}}
function feedback(){el('h1','反馈问题与建议');const s=el('section');el('h2','提交反馈',s);el('p','只发送你填写的内容及主动选择的附件。请删除密码、令牌、服务器地址等敏感信息；附件最大5 MB。反馈会由管理员处理，请保管编号和查询凭证。',s);const content=field(s,'反馈内容','textarea');content.maxLength=10000;const file=field(s,'附件（可选）','file');const confirm=field(s,'我已检查内容与附件，确认发送','checkbox');const result=el('div',undefined,s);button('确认提交',async()=>{if(!confirm.checked)throw Error('请先确认发送内容');const data=new FormData();data.append('content',content.value);data.append('confirmed','yes');if(file.files[0])data.append('attachment',file.files[0]);const r=await api('/api/v1/feedback',{method:'POST',body:data});result.replaceChildren();el('p','反馈编号：'+r.id,result);el('p','查询凭证：'+r.token,result);content.value='';file.value='';confirm.checked=false},s);const q=el('section');el('h2','查询处理进度',q);const id=field(q,'反馈编号'),key=field(q,'查询凭证');const out=el('div',undefined,q);button('查询',async()=>{const f=await post('/api/v1/feedback/lookup',{id:id.value,token:key.value});out.replaceChildren();showFeedback(f,out)},q)}
({ '/':portal,'/help':help,'/feedback':feedback }[location.pathname]||portal)();
`
