'use strict';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=value=>Number(value||0).toLocaleString('zh-CN');
const date=value=>!value||String(value).startsWith('0001-')?'暂无记录':new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
const bytes=value=>value>=1073741824?(value/1073741824).toFixed(2)+' GB':(value/1048576).toFixed(1)+' MB';
const badge=(text,tone='')=>'<span class="badge '+tone+'"><i></i>'+esc(text)+'</span>';
let token='',demo=new URLSearchParams(location.search).get('demo')==='1',page='overview',data=null,loading=false,revision=0,statsDate='';
const nav=[['overview','◫','服务总览'],['releases','↓','版本与安装包'],['announcements','≋','公告管理'],['feedback','▤','用户反馈'],['stats','▥','运营数据']];
const usageOperations=[['gui_script','脚本执行'],['gui_diagnose','AI 定位'],['gui_archive','归档'],['gui_upload','文件上传'],['gui_download','文件下载'],['gui_generate','命令生成'],['cli_exec','exec'],['cli_upload','file 上传'],['cli_download','file 下载'],['cli_diagnose','diagnose'],['cli_knowledge_list','knowledge 列表'],['cli_knowledge_search','knowledge 搜索'],['cli_knowledge_read','knowledge 读取']];
const usageSingles=[['gui_script_created','脚本创建'],['gui_knowledge_opened','知识文档打开'],['gui_knowledge_search','知识搜索'],['gui_knowledge_found','搜索有结果'],['gui_knowledge_empty','搜索无结果'],['gui_command_typed','生成命令发送'],['cli_policy_command','命令策略拒绝'],['cli_policy_target','目标策略拒绝'],['cli_policy_path','路径策略拒绝'],['cli_policy_size','大小限制拒绝'],['cli_recovery_started','连接恢复尝试'],['cli_recovery_success','连接恢复成功'],['cli_recovery_failure','连接恢复失败']];
function usagePanel(prefix,day){
 const u=data.stats.daily[day]?.usage||{};
 const n=key=>u[key]||0;
 const result=(label,count,tone='neutral')=>'<span class="activity-result '+tone+(count===0?' is-zero':'')+'">'+esc(label)+' <b>'+num(count)+'</b></span>';
 const outcome=key=>result('完成',n(key+'_success'),'success')+result('失败',n(key+'_failure'),'failure')+(prefix==='gui_'?result('取消',n(key+'_cancelled'),'cancelled'):'');
 const groups=prefix==='gui_'?[
  ['脚本', [['创建脚本',n('gui_script_created'),'<span class="activity-description">成功保存的脚本</span>'],['执行脚本',n('gui_script_started'),outcome('gui_script')]]],
  ['排查与沉淀', [['AI 定位',n('gui_diagnose_started'),outcome('gui_diagnose')],['归档',n('gui_archive_started'),outcome('gui_archive')]]],
  ['知识', [['知识搜索',n('gui_knowledge_search'),result('有结果',n('gui_knowledge_found'),'success')+result('无结果',n('gui_knowledge_empty'))],['打开文档',n('gui_knowledge_opened'),'<span class="activity-description">成功打开的知识文档</span>']]],
  ['文件传输', [['上传文件',n('gui_upload_started'),outcome('gui_upload')],['下载文件',n('gui_download_started'),outcome('gui_download')]]],
  ['命令', [['生成命令',n('gui_generate_started'),outcome('gui_generate')],['发送命令',n('gui_command_typed'),'<span class="activity-description">已发送至终端</span>']]]
 ]:[
  ['执行与传输', [['命令执行',n('cli_exec_started'),outcome('cli_exec')],['上传文件',n('cli_upload_started'),outcome('cli_upload')],['下载文件',n('cli_download_started'),outcome('cli_download')]]],
  ['诊断与知识', [['故障诊断',n('cli_diagnose_started'),outcome('cli_diagnose')],['知识列表',n('cli_knowledge_list_started'),outcome('cli_knowledge_list')],['知识搜索',n('cli_knowledge_search_started'),outcome('cli_knowledge_search')],['知识读取',n('cli_knowledge_read_started'),outcome('cli_knowledge_read')]]],
  ['策略与恢复', [['策略拒绝',['cli_policy_command','cli_policy_target','cli_policy_path','cli_policy_size'].reduce((sum,key)=>sum+n(key),0),result('命令',n('cli_policy_command'))+result('目标',n('cli_policy_target'))+result('路径',n('cli_policy_path'))+result('大小',n('cli_policy_size'))],['连接恢复',n('cli_recovery_started'),result('成功',n('cli_recovery_success'),'success')+result('失败',n('cli_recovery_failure'),'failure')]]]
 ];
 const rows=groups.flatMap(([group,items])=>['<tr class="activity-group"><th colspan="3">'+esc(group)+'</th></tr>',...items.map(([label,count,results])=>'<tr><td>'+esc(label)+'</td><td class="activity-count"><strong>'+num(count)+'</strong></td><td><div class="activity-results">'+results+'</div></td></tr>')]);
 const content=day?'<div class="activity-table">'+table(['功能','使用次数','结果次数'],rows)+'</div>':'<div class="empty">暂无授权功能统计</div>';
 return '<section class="panel usage-panel"><div class="panel-head"><div><h2>'+ (prefix==='gui_'?'桌面功能':'CLI 与策略')+'</h2><p>仅常规授权 · 单位：次</p></div></div>'+content+'<div class="notice">'+(prefix==='gui_'?'AI 定位完成不代表故障解决；发送命令不代表执行成功。':'完成表示调用成功；CLI 强制结束可能没有结果计数。')+'</div></section>';
}

let samples;
function mockData(){
 const now=new Date(); const ago=days=>new Date(now.getTime()-days*86400000).toISOString();
 const daily={};[92,106,101,124,138,127,146].forEach((v,i)=>{const d=ago(6-i).slice(0,10);daily[d]={reporting:{standard:v-24,minimal:24},Active:v,Connections:v*8+17,Connected:v*8-5,CtrlK:v*3+11,QuickCommands:v*4+9,usage:Object.fromEntries(usageOperations.flatMap(([key],j)=>[[key+'_started',v+j*3],[key+'_success',v+j*3-(key.startsWith('cli_')?6:8)],[key+'_failure',6],[key+'_cancelled',key.startsWith('cli_')?0:2]]).concat([['gui_script_created',v],['gui_knowledge_opened',v*2],['gui_knowledge_search',v],['gui_knowledge_found',v-9],['gui_knowledge_empty',9],['gui_command_typed',v],['cli_policy_command',12],['cli_policy_target',3],['cli_policy_path',5],['cli_policy_size',2],['cli_recovery_started',8],['cli_recovery_success',7],['cli_recovery_failure',1]])),upgrades:{'download:success':i*3+4,'install:success':i*2+3,'download:failure':i===4?2:0}}});
 return {status:{lastSuccess:ago(0),error:'',inProgress:false,storageBytes:824180736},releases:[['v1.10.5',0],['v1.10.4',4],['v1.10.3',12]].map(([v,n])=>({tag_name:v,name:v,published_at:ago(n),body:'演示更新说明：优化工作台交互与连接稳定性。',assets:[{name:'opscopilot-windows.zip',size:81264640},{name:'opscopilot.exe',size:146800640}]})),announcements:[{id:'notice-001',text:'新版本已同步，建议在完成当前操作后检查更新。',url:location.origin+'/#downloads',order:1,startsAt:ago(2),endsAt:ago(-12)},{id:'notice-002',text:'团队知识分享：排查完成后，记得补充根因与解决方案。',url:location.origin+'/help',order:2,startsAt:ago(1),endsAt:ago(-5)},{id:'notice-003',text:'服务维护提醒：请提前下载所需安装包，避免维护期间等待。',url:'',order:3,startsAt:ago(-2),endsAt:ago(-3)},{id:'notice-004',text:'欢迎参与 OpsCopilot 内网试用，问题与建议可通过反馈入口提交。',url:'',order:4,startsAt:ago(20),endsAt:ago(3)}],feedback:[{id:'FB-DEMO-008',content:'希望快捷命令支持按业务分组\n常用命令越来越多，按业务或环境分组会更方便查找。',createdAt:ago(0),status:'待处理',reply:''},{id:'FB-DEMO-007',content:'跳板机重连后，文件面板未自动刷新\n网络短暂中断后已恢复终端，文件列表需要手动刷新。',createdAt:ago(1),status:'处理中',reply:'已收到，正在检查连接恢复后的刷新流程。',attachment:'demo.txt'},{id:'FB-DEMO-006',content:'Ctrl+K 历史搜索希望支持关键词高亮',createdAt:ago(2),status:'待处理',reply:''},{id:'FB-DEMO-005',content:'内网下载体验很好，希望补充初次安装说明',createdAt:ago(3),status:'已解决',reply:'已在使用帮助中补充安装与连接说明。'},{id:'FB-DEMO-004',content:'建议公告支持直接打开使用帮助',createdAt:ago(5),status:'已解决',reply:'公告已支持设置同一内网服务地址的详情链接。'}],stats:{coverage:'仅代表同意采集的安装实例；安装量不等于人数。最简授权仅计入活跃与版本，功能计数仅来自常规授权。版本分布按90天内实例/版本去重。',versions:{'v1.10.5':186,'v1.10.4':52,'v1.10.3':18},daily}};
}
async function request(path,options={}){
 if(demo)throw Error('演示模式不会请求管理接口');
 const headers={...options.headers};if(path.startsWith('/api/admin/'))headers.Authorization='Bearer '+token;
 const response=await fetch(path,{...options,headers});
 if(!response.ok){const body=await response.json().catch(()=>null);throw Error(response.status===401?'管理员令牌无效或已失效':body?.error||'请求失败（'+response.status+'）');}
 return response.json();
}
const post=(path,body)=>request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3500)}
function table(headers,rows,empty='暂无数据'){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>'+(rows.length?'':'<div class="empty">'+esc(empty)+'</div>')+'</div>'}
function panel(title,content,action='',note=''){return '<section class="panel"><div class="panel-head"><h2>'+title+'</h2>'+action+'</div>'+content+(note?'<div class="notice">'+esc(note)+'</div>':'')+'</section>'}
function action(label,id,secondary=false){return '<button data-action="'+id+'"'+(secondary?' class="secondary"':'')+'>'+label+'</button>'}
function heading(title,description,actions=''){return '<div class="page-heading"><div><h1>'+title+'</h1><p>'+description+'</p></div><div class="actions">'+actions+'</div></div>'}
function metric(label,value,note){return '<article class="metric"><label>'+label+'</label><strong>'+esc(value)+'</strong><small>'+note+'</small></article>'}
function dates(){return Object.keys(data.stats.daily||{}).sort().reverse()}
function latestDay(){return data.stats.daily?.[dates()[0]]||{}}
function announcementState(a){const now=Date.now();return new Date(a.startsAt)>now?['待生效','blue']:new Date(a.endsAt)<=now?['已结束','']:['展示中','good']}
function syncSummary(){const s=data.status;return '<div class="panel-body"><dl class="summary-list"><div><dt>GitHub 同步</dt><dd>'+badge(s.inProgress?'同步中':s.error?'同步失败':'空闲',s.inProgress?'blue':s.error?'bad':'good')+'</dd></div><div><dt>最近成功同步</dt><dd>'+date(s.lastSuccess)+'</dd></div><div><dt>客户端当前版本</dt><dd>'+esc(s.latestVersion||'尚无版本')+'</dd></div><div><dt>存储占用</dt><dd>'+bytes(s.storageBytes)+'</dd></div></dl><div class="health-note">'+esc(s.error||'手工上传与 GitHub 同步均会在文件完整后发布；同步失败不会影响已发布版本。')+'</div></div>'}
function trend(){const days=dates().slice(0,7).reverse(),max=Math.max(1,...days.map(d=>data.stats.daily[d].Active||0));if(!days.length)return '<div class="empty">暂无授权实例的日统计</div>';return '<div class="panel-body"><svg class="trend" viewBox="0 0 560 170" role="img" aria-label="最近七个有记录日期的活跃安装数柱状图">'+days.map((d,i)=>{const v=data.stats.daily[d].Active||0,h=v/max*105,x=i*78+20;return '<g><title>'+d+'：'+v+' 个活跃安装</title><text x="'+(x+23)+'" y="'+(133-h)+'" text-anchor="middle">'+v+'</text><rect x="'+x+'" y="'+(140-h)+'" width="46" height="'+h+'" rx="3" class="'+(i===days.length-1?'last':'')+'"></rect><text x="'+(x+23)+'" y="162" text-anchor="middle">'+d.slice(5)+'</text></g>'}).join('')+'</svg></div>'}
function versions(){const entries=Object.entries(data.stats.versions||{}).sort((a,b)=>b[1]-a[1]),total=entries.reduce((s,[,n])=>s+n,0);return '<div class="panel-body">'+(entries.length?entries.map(([v,n])=>'<div class="version-row"><div><strong>'+esc(v)+'</strong><span>'+num(n)+' 实例 / '+Math.round(n/total*100)+'%</span></div><progress max="'+total+'" value="'+n+'"></progress></div>').join(''):'<div class="empty">暂无版本分布数据</div>')+'</div>'}
function overview(){const d=latestDay(),pending=data.feedback.filter(f=>f.status!=='已解决').length,active=data.announcements.filter(a=>announcementState(a)[0]==='展示中').length;return heading('服务总览','查看镜像服务状态、授权使用情况与待处理事项。',action('刷新数据','refresh',true))+ '<div class="metric-grid">'+metric('最近统计日活跃安装',num(d.Active),dates()[0]||'尚无统计')+metric('连接成功 / 发起',num(d.Connected)+' / '+num(d.Connections),d.Connections?'<em>'+((d.Connected/d.Connections)*100).toFixed(1)+'% 成功率</em>':'暂无连接计数')+metric('待跟进反馈',num(pending),data.feedback.filter(f=>f.status==='待处理').length+' 待处理 · '+data.feedback.filter(f=>f.status==='处理中').length+' 处理中')+metric('当前展示公告',num(active),data.announcements.length+' 条公告 · '+data.releases.length+' 个镜像版本')+'</div><div class="two-cols">'+panel('活跃安装趋势',trend(),'<span class="range-note">最近 7 个有记录日期</span>')+panel('镜像服务',syncSummary(),action('立即同步','sync',true))+'</div><div class="two-cols">'+panel('最近反馈',feedbackTable(data.feedback.slice(0,4)),action('查看全部','goto-feedback',true))+panel('版本分布',versions(),'<span class="range-note">近 90 天</span>',data.stats.coverage)+'</div>'}
function releasesPage(){return heading('版本与安装包','上传安装包直接发布到内网；也可从 GitHub 同步。客户端从本服务下载。',action('刷新','refresh',true)+action('从 GitHub 同步','sync',true)+action('上传新版本','upload-release'))+panel('发布概况',syncSummary())+panel('已发布版本',table(['版本','发布时间','来源','安装包','体积','操作'],data.releases.map(r=>'<tr><td><strong>'+esc(r.tag_name)+'</strong>'+(r.tag_name===data.status.latestVersion?'<small>客户端当前版本</small>':'')+'</td><td>'+date(r.published_at)+'</td><td>'+badge(r.source==='upload'?'手工上传':'GitHub 同步',r.source==='upload'?'blue':'good')+'</td><td>'+r.assets.map(a=>esc(a.name)).join('<br>')+'</td><td>'+r.assets.map(a=>bytes(a.size)).join('<br>')+'</td><td><button class="ghost" data-notes="'+esc(r.tag_name)+'">更新说明</button></td></tr>'),'尚无已发布版本'),'<span class="muted">'+data.releases.length+' 个版本</span>')}
function announcementTable(){return table(['公告内容','展示状态','展示时间','排序','操作'],data.announcements.slice().sort((a,b)=>a.order-b.order).map(a=>{const [state,tone]=announcementState(a);return '<tr><td class="feedback-content"><strong>'+esc(a.text)+'</strong><small>'+esc(a.url||'未设置详情链接')+'</small></td><td>'+badge(state,tone)+'</td><td>'+date(a.startsAt)+'<small>至 '+date(a.endsAt)+'</small></td><td>'+a.order+'</td><td><button class="ghost" data-notice="'+esc(a.id)+'">编辑</button><button class="ghost danger" data-delete="'+esc(a.id)+'">删除</button></td></tr>'}),'暂无公告，点击“新建公告”发布第一条。')}
function announcementsPage(){return heading('公告管理','设置客户端底栏展示的消息、详情链接及有效时间。',action('新建公告','new-notice'))+panel('公告列表',announcementTable(),'<span class="muted">'+data.announcements.length+' 条公告</span>','公告只在有效期内展示，按排序值从小到大排列。')}
function feedbackTable(items){return table(['反馈内容','状态','提交时间','操作'],items.map(f=>'<tr><td class="feedback-content"><strong>'+esc(f.content.split('\n')[0])+'</strong><small>'+esc(f.id)+(f.attachment?' · 含附件':'')+'</small></td><td>'+badge(f.status,f.status==='已解决'?'good':f.status==='处理中'?'blue':'warn')+'</td><td>'+date(f.createdAt)+'</td><td><button class="ghost" data-feedback="'+esc(f.id)+'">查看与回复</button></td></tr>'),'没有符合条件的反馈')}
function feedbackPage(){return heading('用户反馈','查看用户主动提交的内容，跟进处理状态与回复。')+panel('反馈列表','<div class="filter-bar"><input id="feedback-search" type="search" placeholder="搜索反馈内容或编号" aria-label="搜索反馈"><select id="feedback-status" aria-label="反馈状态"><option>全部状态</option><option>待处理</option><option>处理中</option><option>已解决</option></select><span class="muted">共 '+data.feedback.length+' 条</span></div><div id="feedback-rows">'+feedbackTable(data.feedback)+'</div>')}
const phases={'download':'下载','install':'安装','check':'检查','startup':'新版本启动','rollback':'回滚'},results={success:'成功',failed:'失败',failure:'失败',cancelled:'取消',no_update:'无需更新'};
function upgradeText(upgrades){return Object.entries(upgrades||{}).filter(([,n])=>n).map(([k,v])=>{const [p,r]=k.split(':');return '<span class="badge '+(r==='success'?'good':'warn')+'">'+esc(phases[p]||p)+' '+esc(results[r]||r)+' '+num(v)+'</span>'}).join(' ' )||'—'}
function statsMetric(label,value,unit,note,comparison=''){
 return '<article class="metric stats-metric"><label>'+label+'</label><div class="metric-value"><strong>'+esc(value)+'</strong><span>'+unit+'</span></div><div class="metric-caption"><small>'+note+'</small>'+comparison+'</div></article>';
}
function statsPage(){
 const ds=dates();if(!ds.includes(statsDate))statsDate=ds[0]||'';
 const d=data.stats.daily[statsDate]||{},previous=data.stats.daily[ds[ds.indexOf(statsDate)+1]];
 const delta=key=>{if(!previous)return '';const n=(d[key]||0)-(previous[key]||0);return '<span class="metric-delta" title="较上一统计日 '+esc(ds[ds.indexOf(statsDate)+1])+'">'+(n>0?'↑ +':n<0?'↓ ':'→ ')+num(n)+'</span>'};
 const value=key=>statsDate?num(d[key]):'—';
 const connectionNote=d.Connections?'成功 '+num(d.Connected)+' 次 · '+((d.Connected||0)/d.Connections*100).toFixed(1)+'%':'暂无连接发起';
 const history=table(['日期','活跃安装','连接发起','连接成功','Ctrl + K','快捷命令','升级阶段结果'],ds.map(day=>{const v=data.stats.daily[day];return '<tr'+(day===statsDate?' class="selected-stat-day"':'')+'><td class="mono">'+day+'</td>'+[v.Active,v.Connections,v.Connected,v.CtrlK,v.QuickCommands].map(x=>'<td class="numeric">'+num(x)+'</td>').join('')+'<td><div class="upgrades">'+upgradeText(v.upgrades)+'</div></td></tr>'}));
 return '<div class="stats-page">'+heading('运营数据','了解授权使用情况、功能使用与升级结果。',action('刷新数据','refresh',true))+
 '<div class="stats-toolbar"><div class="date-control"><label for="usage-date">统计日期</label><select id="usage-date"'+(!ds.length?' disabled':'')+'>'+(ds.length?ds.map(day=>'<option'+(day===statsDate?' selected':'')+'>'+esc(day)+'</option>').join(''):'<option>暂无数据</option>')+'</select><span class="date-scope">按日汇总 · 箭头对比上一统计日</span></div><span class="stats-scope"><i></i>仅统计授权安装</span></div>'+
 '<div class="metric-grid">'+statsMetric('活跃安装',value('Active'),'个','含常规与最简授权',delta('Active'))+statsMetric('连接发起',value('Connections'),'次',connectionNote,delta('Connections'))+statsMetric('Ctrl + K',value('CtrlK'),'次','不含输入内容',delta('CtrlK'))+statsMetric('快捷命令',value('QuickCommands'),'次','不含命令内容',delta('QuickCommands'))+'</div>'+
 panel('上报方式','<div class="reporting-grid"><div class="reporting-standard"><span>常规上报</span><strong>'+ (d.reporting?num(d.reporting.standard):'—') +'<small> 个安装</small></strong><p>分享活跃、版本与功能统计</p></div><div class="reporting-minimal"><span>最简上报</span><strong>'+ (d.reporting?num(d.reporting.minimal):'—') +'<small> 个安装</small></strong><p>仅分享活跃、版本及必要授权信息</p></div><div class="reporting-disabled"><span>完全关闭</span><strong>无法统计</strong><p>不发送数据，服务器无法获知选择</p></div></div>','<span class="range-note">所选统计日 · 按安装去重</span>','按当日收到的最新授权记录分类，不代表客户端此刻的设置；完全关闭与未授权不发送数据，不能由未上报推断为拒绝。旧的匿名汇总未保留分类时显示 —。')+
 '<div class="stats-analytics">'+panel('活跃安装趋势',trend(),'<span class="range-note">最近 7 个有记录日期 · 个</span>')+panel('版本分布',versions(),'<span class="range-note">近 90 天</span>','同一安装在不同版本分别计入，分布不等于当前在用版本。')+'</div>'+
 '<div class="stats-section-heading"><h2>功能使用明细</h2><div class="stats-legend"><span><i class="legend-success"></i>完成</span><span><i class="legend-failure"></i>失败</span><span><i class="legend-cancelled"></i>取消</span></div></div><div class="stats-usage-grid" id="usage-panels">'+usagePanel('gui_',statsDate)+usagePanel('cli_',statsDate)+'</div>'+
 '<details class="stats-history panel"><summary><span>每日汇总</span><small>'+ds.length+' 个统计日 · 查看连接与升级明细</small><b aria-hidden="true">⌄</b></summary>'+history+'</details>'+
 '<details class="stats-definition"><summary>统计口径与数据范围</summary><p>'+esc(data.stats.coverage)+'</p><p>顶部指标和功能明细对应所选统计日；趋势固定显示最近 7 个有记录日期。箭头表示与上一有记录日期的数值变化。未上报的数据不在统计范围内，不能据此推算全部用户使用情况。</p></details></div>';
}
function render(){
	if(demo&&data?.status&&!data.status.latestVersion)data.status.latestVersion=data.releases[0]?.tag_name||'';
 $('#navigation').innerHTML=nav.map(([id,icon,title])=>'<button data-page="'+id+'" class="'+(id===page?'active':'')+'"'+(id===page?' aria-current="page"':'')+'><span>'+icon+'</span>'+title+'</button>').join('');
 $('#breadcrumb').textContent=nav.find(n=>n[0]===page)[2];
 $('#session-controls').innerHTML=demo?badge('演示模式','warn')+action('返回真实服务','exit-demo',true):token?badge('已登录','good')+action('退出','logout',true):badge('未登录');
 if(!data){login();return;}
 const banner=demo?'<div class="demo-banner"><div><strong>演示数据</strong>以下数据为模拟示例，编辑只在当前页面生效，不会写入真实服务。</div>'+action('重置示例','reset-demo',true)+'</div>':'';
 $('#workspace').innerHTML=banner+({overview,releases:releasesPage,announcements:announcementsPage,feedback:feedbackPage,stats:statsPage}[page])();
}
function login(){ $('#workspace').innerHTML='<div class="login"><section class="panel"><div class="panel-body"><div class="login-kicker">OPSCOPILOT / SERVICE CONSOLE</div><h1>管理内网服务</h1><p>查看版本同步、维护公告、处理反馈与了解授权使用情况。</p><form id="login-form"><label for="admin-token">管理员令牌</label><input id="admin-token" type="password" autocomplete="off" required placeholder="输入管理员令牌"><button type="submit">登录控制台</button><p id="login-error" class="error" role="alert"></p></form><p class="range-note">令牌仅保存在当前页面内存中，刷新后需要重新登录。</p></div><div class="sample"><h3>先看看完整管理效果</h3><p>使用模拟的版本、公告、反馈和运营统计，体验各个工作区。</p>'+action('打开演示控制台','enter-demo',true)+'</div></section></div>'; }
async function load(){const version=++revision;loading=true;try{const values=await Promise.all(['/api/admin/status','/api/v1/releases','/api/admin/announcements','/api/admin/feedback','/api/admin/stats'].map(p=>request(p)));if(version!==revision)return;data={status:values[0],releases:values[1]||[],announcements:values[2]||[],feedback:(values[3]||[]).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)),stats:values[4]};render()}finally{loading=false}}
function startDemo(){revision++;token='';demo=true;samples=mockData();data=samples;history.replaceState(null,'','/admin?demo=1');render()}
function logout(){revision++;token='';data=null;demo=false;history.replaceState(null,'','/admin');page='overview';$('#editor').close();render()}
async function afterWrite(message){try{await load();toast(message)}catch{render();toast(message+'；列表刷新失败，请手动刷新')}}
function localDate(value){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function input(label,name,value='',type='text',required=false){return '<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'"'+(required?' required':'')+'></label>'}
function openEditor(html,save,label='保存'){const dialog=$('#editor');$('#editor-body').innerHTML=html;$('#editor-error').textContent='';$('#editor-form button[type=submit]').textContent=label;$('#editor-form button[type=submit]').hidden=!save;dialog.oncancel=event=>{if($('#editor-form button[type=submit]').disabled)event.preventDefault()};$('#editor-form').onsubmit=async event=>{event.preventDefault();const submit=$('#editor-form button[type=submit]'),cancel=$('#cancel-editor');submit.disabled=true;cancel.disabled=true;try{await save(new FormData(event.target));dialog.close();render()}catch(e){$('#editor-error').textContent=e.message}finally{submit.disabled=false;cancel.disabled=false}};dialog.showModal()}
function uploadMultipart(form){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/admin/releases');xhr.timeout=30*60*1000;xhr.setRequestHeader('Authorization','Bearer '+token);xhr.upload.onprogress=e=>{const label=$('#upload-progress');if(label)label.textContent=e.lengthComputable?'上传中 '+Math.round(e.loaded/e.total*100)+'%':'正在上传安装包…'};xhr.onload=()=>{let result;try{result=JSON.parse(xhr.responseText)}catch{}if(xhr.status===201)resolve(result);else reject(Error(xhr.status===401?'管理员令牌无效或已失效':result?.error||'上传失败（'+xhr.status+'）'))};xhr.onerror=()=>reject(Error('网络中断，版本未确认发布，请刷新列表检查'));xhr.ontimeout=()=>reject(Error('上传超时，请刷新版本列表确认是否发布'));xhr.send(form)})}
function editRelease(){
 const current=data.status.latestVersion||data.releases[0]?.tag_name||'';
 const match=/^v(\d+)\.(\d+)\.(\d+)$/.exec(current);
 const next=match?'v'+match[1]+'.'+match[2]+'.'+(Number(match[3])+1):'';
 const html='<h2>上传新版本</h2><p>安装包从此页面传到内网服务。全部上传并校验完成后，客户端才会看到新版本；发布后版本号不能覆盖。</p>'+input('版本号','version',next,'text',true)+'<label>更新说明<textarea name="notes" maxlength="65536" required placeholder="说明本次修复或新增内容"></textarea></label><div class="upload-fields"><label>Windows 更新包 · '+(demo?'演示可不选文件':'必填')+'<input name="windows" type="file" accept=".zip"'+(demo?'':' required')+'></label><label>Windows 独立程序 · 可选<input name="exe" type="file" accept=".exe"></label><label>内网服务 Linux amd64 · 可选<input name="linux_amd64" type="file"></label><label>内网服务 Linux arm64 · 可选<input name="linux_arm64" type="file"></label></div><p id="upload-progress" class="upload-progress" role="status">ZIP 包内须有根目录下的 opscopilot.exe；单文件不超过 512 MB，总计不超过 1 GB。</p>';
 openEditor(html,async form=>{
  const version=String(form.get('version')||'').trim(),notes=String(form.get('notes')||'').trim();
  if(!/^v(0|[1-9]\d{0,8})\.(0|[1-9]\d{0,8})\.(0|[1-9]\d{0,8})$/.test(version))throw Error('版本号应为 v主.次.修订，例如 v1.11.4');
  if(!notes)throw Error('请填写更新说明');
  const payload=new FormData();payload.append('version',version);payload.append('notes',notes);
  let total=0;
  for(const key of ['windows','exe','linux_amd64','linux_arm64']){
   const file=form.get(key);
   if(file instanceof File&&file.size){if(file.size>512*1048576)throw Error('单个安装包不能超过 512 MB');total+=file.size;payload.append(key,file)}
  }
  if(!payload.has('windows')&&!demo)throw Error('请选择 Windows ZIP 更新包');
  if(total>1023*1048576)throw Error('安装包合计不能超过 1 GB');
  if(demo){const now=new Date().toISOString();data.releases.unshift({tag_name:version,source:'upload',name:version,published_at:now,body:notes,assets:[{name:'opscopilot-windows.zip',size:total||81264640}]});data.status.latestVersion=version;toast('演示版本已添加，未上传任何文件')}
  else{await uploadMultipart(payload);await afterWrite('新版本已发布，客户端可从内网检查更新')}
 },'上传并发布');
}
function editNotice(id){const a=data.announcements.find(a=>a.id===id)||{text:'',url:'',order:1,startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+7*86400000).toISOString()};openEditor('<h2>'+ (id?'编辑公告':'新建公告')+'</h2><p>'+ (demo?'演示修改仅在当前页面生效。':'设置有效期及底栏展示顺序。')+'</p><label>公告正文<textarea name="text" maxlength="500" required>'+esc(a.text)+'</textarea></label>'+input('详情链接（本站地址，可留空）','url',a.url,'url')+'<div class="form-cols">'+input('开始时间','start',localDate(a.startsAt),'datetime-local',true)+input('结束时间','end',localDate(a.endsAt),'datetime-local',true)+'</div>'+input('排序值','order',a.order,'number',true),async form=>{const row={id:id||'',text:form.get('text').trim(),url:form.get('url').trim(),order:Number(form.get('order')),startsAt:new Date(form.get('start')).toISOString(),endsAt:new Date(form.get('end')).toISOString()};if(!row.text)throw Error('请填写公告正文');if(new TextEncoder().encode(row.text).length>1000)throw Error('公告内容过长，请精简至约 330 个汉字以内');if(!Number.isInteger(row.order))throw Error('排序值应为整数');if(row.endsAt<=row.startsAt)throw Error('结束时间应晚于开始时间');if(row.url&&new URL(row.url).origin!==location.origin)throw Error('详情链接必须指向本站地址');if(demo){row.id ||= 'notice-demo-'+Date.now();const i=data.announcements.findIndex(a=>a.id===row.id);i<0?data.announcements.push(row):data.announcements.splice(i,1,row);toast('演示公告已保存')}else{const saved=await post('/api/admin/announcements',row);const i=data.announcements.findIndex(a=>a.id===saved.id);i<0?data.announcements.push(saved):data.announcements.splice(i,1,saved);await afterWrite('公告已保存')}})}
function editFeedback(id){const f=data.feedback.find(f=>f.id===id);openEditor('<h2>处理用户反馈</h2><p>'+esc(f.id)+' · '+date(f.createdAt)+'</p><pre>'+esc(f.content)+'</pre>'+(f.attachment?'<button type="button" class="secondary" data-attachment="'+esc(f.id)+'">下载附件'+(demo?'（演示不可下载）':'')+'</button>':'')+'<label>处理状态<select name="status">'+['待处理','处理中','已解决'].map(s=>'<option'+(s===f.status?' selected':'')+'>'+s+'</option>').join('')+'</select></label><label>回复内容<textarea name="reply" maxlength="10000">'+esc(f.reply)+'</textarea></label>',async form=>{const row={status:form.get('status'),reply:form.get('reply')};if(new TextEncoder().encode(row.reply).length>10000)throw Error('回复内容过长，请精简');if(demo){Object.assign(f,row);toast('演示处理结果已保存')}else{await post('/api/admin/feedback/'+encodeURIComponent(id),row);Object.assign(f,row);await afterWrite('处理结果已保存')}},'保存处理结果')}
async function handleAction(name){switch(name){case 'enter-demo':startDemo();break;case 'exit-demo':case 'logout':logout();break;case 'reset-demo':data=samples=mockData();render();toast('示例已重置');break;case 'refresh':if(demo){render();toast('已刷新演示数据')}else{await load();toast('数据已刷新')}break;case 'upload-release':editRelease();break;case 'new-notice':editNotice();break;case 'goto-feedback':page='feedback';render();break;case 'sync':if(demo){data.status.lastSuccess=new Date().toISOString();toast('演示同步完成，真实服务未执行同步');render()}else{await post('/api/admin/sync',{});await load();toast('同步已排队，请稍后刷新查看结果')}break}}
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b||b.disabled)return;try{if(b.dataset.page){page=b.dataset.page;render()}else if(b.dataset.action){b.disabled=true;await handleAction(b.dataset.action)}else if(b.dataset.notice)editNotice(b.dataset.notice);else if(b.dataset.feedback)editFeedback(b.dataset.feedback);else if(b.dataset.notes){const r=data.releases.find(r=>r.tag_name===b.dataset.notes);openEditor('<h2>'+esc(r.tag_name)+' 更新说明</h2><pre>'+esc(r.body||'暂无更新说明')+'</pre>',null)}else if(b.dataset.delete){const id=b.dataset.delete;openEditor('<h2>删除公告</h2><p>删除后客户端将不再展示这条公告。</p><pre>'+esc(data.announcements.find(a=>a.id===id).text)+'</pre>',async()=>{if(demo){data.announcements=data.announcements.filter(a=>a.id!==id);toast('演示公告已删除')}else{await request('/api/admin/announcements/'+encodeURIComponent(id),{method:'DELETE'});data.announcements=data.announcements.filter(a=>a.id!==id);await afterWrite('公告已删除')}},'确认删除')}else if(b.dataset.attachment){if(demo){toast('演示附件仅用于展示，不包含实际文件');return;}const r=await fetch('/api/admin/feedback/'+encodeURIComponent(b.dataset.attachment)+'/attachment',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('附件下载失败');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='feedback-attachment.bin';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}}catch(e){toast(e.message)}finally{b.disabled=false}});
document.addEventListener('submit',async event=>{if(event.target.id!=='login-form')return;event.preventDefault();if(loading)return;const b=event.target.querySelector('button');b.disabled=true;token=$('#admin-token').value.trim();try{await load()}catch(e){token='';$('#login-error').textContent=e.message}finally{b.disabled=false}});
function filterFeedback(){if(!$('#feedback-rows'))return;const q=$('#feedback-search').value.toLowerCase(),s=$('#feedback-status').value;$('#feedback-rows').innerHTML=feedbackTable(data.feedback.filter(f=>(s==='全部状态'||f.status===s)&&(f.content+' '+f.id).toLowerCase().includes(q)))}
document.addEventListener('input',event=>{if(event.target.id==='feedback-search')filterFeedback()});
document.addEventListener('change',event=>{if(event.target.id==='feedback-status')filterFeedback()});
$('#cancel-editor').onclick=()=>$('#editor').close();
if(demo)startDemo();else render();

document.addEventListener('change',event=>{ if(event.target.id==='usage-date') { statsDate=event.target.value;render();$('#usage-date').focus(); } });
