// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {sessionmanager} from '../models';
import {script} from '../models';
import {recorder} from '../models';
import {sshclient} from '../models';

export function AskAI(arg1:string):Promise<string>;

export function AskTroubleshoot(arg1:string,arg2:boolean):Promise<string>;

export function Broadcast(arg1:Array<string>,arg2:string):Promise<void>;

export function CancelSession():Promise<string>;

export function CloseSession(arg1:string):Promise<void>;

export function Connect(arg1:main.ConnectConfig):Promise<main.ConnectResult>;

export function ConnectWithID(arg1:main.ConnectConfig,arg2:string):Promise<main.ConnectResult>;

export function DeleteSavedSession(arg1:string):Promise<string>;

export function DeleteScript(arg1:string):Promise<void>;

export function DuplicateSession(arg1:string):Promise<main.ConnectResult>;

export function ExportScript(arg1:string):Promise<string>;

export function FTCancel(arg1:string):Promise<string>;

export function FTCheck(arg1:string):Promise<string>;

export function FTDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FTList(arg1:string,arg2:string):Promise<string>;

export function FTRemoteMkdir(arg1:string,arg2:string):Promise<string>;

export function FTRemoteReadFile(arg1:string,arg2:string,arg3:number):Promise<string>;

export function FTRemoteRemove(arg1:string,arg2:string):Promise<string>;

export function FTRemoteRename(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FTRemoteWriteFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FTStat(arg1:string,arg2:string):Promise<string>;

export function FTUpload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ForceQuit():Promise<void>;

export function GenerateConclusionWithContext(arg1:string,arg2:string):Promise<string>;

export function GenerateLinuxCommand(arg1:string):Promise<string>;

export function GetCompletions(arg1:string,arg2:number):Promise<string>;

export function GetHighlightRules():Promise<Array<config.HighlightRule>>;

export function GetMCPStatus():Promise<string>;

export function GetQuickCommandGroups():Promise<Array<string>>;

export function GetSavedSessions():Promise<Array<sessionmanager.Session>>;

export function GetScriptList():Promise<Array<script.Script>>;

export function GetScriptRecordingStatus():Promise<script.ScriptStatus>;

export function GetSessionTimeline():Promise<recorder.RecordingSession>;

export function GetSettings():Promise<config.AppConfig>;

export function HasActiveWork():Promise<Record<string, any>>;

export function ImportConfigFromDirectory(arg1:string):Promise<string>;

export function LoadQuickCommands():Promise<Array<config.QuickCommand>>;

export function LoadScript(arg1:string):Promise<script.Script>;

export function LocalList(arg1:string):Promise<string>;

export function LocalMkdir(arg1:string):Promise<string>;

export function LocalRemove(arg1:string):Promise<string>;

export function LocalRename(arg1:string,arg2:string):Promise<string>;

export function LocalStat(arg1:string):Promise<string>;

export function ParseIntent(arg1:string):Promise<Array<main.ConnectConfig>>;

export function PolishRootCause(arg1:string):Promise<string>;

export function ReconnectSession(arg1:string):Promise<main.ConnectResult>;

export function RenameSavedSession(arg1:string,arg2:string):Promise<string>;

export function ReplayScript(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveHighlightRules(arg1:Array<config.HighlightRule>):Promise<string>;

export function SaveQuickCommands(arg1:Array<config.QuickCommand>):Promise<string>;

export function SaveSettings(arg1:config.AppConfig):Promise<string>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function StartScriptRecording(arg1:string,arg2:string,arg3:string):Promise<script.Script>;

export function StartSession(arg1:string):Promise<string>;

export function StopScriptRecording():Promise<script.Script>;

export function StopSession(arg1:string,arg2:string):Promise<string>;

export function UpdateSavedSession(arg1:string,arg2:sshclient.ConnectConfig):Promise<string>;

export function UpdateScript(arg1:script.Script):Promise<void>;

export function UpdateSessionTimeline(arg1:Array<recorder.TimelineEvent>):Promise<string>;

export function Write(arg1:string,arg2:string):Promise<void>;
