// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function AskTroubleshoot(arg1) {
  return window['go']['main']['App']['AskTroubleshoot'](arg1);
}

export function Broadcast(arg1, arg2) {
  return window['go']['main']['App']['Broadcast'](arg1, arg2);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteSavedSession(arg1) {
  return window['go']['main']['App']['DeleteSavedSession'](arg1);
}

export function DuplicateSession(arg1) {
  return window['go']['main']['App']['DuplicateSession'](arg1);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GenerateConclusionWithContext(arg1, arg2) {
  return window['go']['main']['App']['GenerateConclusionWithContext'](arg1, arg2);
}

export function GenerateLinuxCommand(arg1) {
  return window['go']['main']['App']['GenerateLinuxCommand'](arg1);
}

export function GetCompletions(arg1, arg2) {
  return window['go']['main']['App']['GetCompletions'](arg1, arg2);
}

export function GetJavaMonitorSnapshot(arg1, arg2) {
  return window['go']['main']['App']['GetJavaMonitorSnapshot'](arg1, arg2);
}

export function GetJavaThreadStateCounts(arg1, arg2) {
  return window['go']['main']['App']['GetJavaThreadStateCounts'](arg1, arg2);
}

export function GetJavaTopCPUThreads(arg1, arg2) {
  return window['go']['main']['App']['GetJavaTopCPUThreads'](arg1, arg2);
}

export function GetSavedSessions() {
  return window['go']['main']['App']['GetSavedSessions']();
}

export function GetSessionTimeline() {
  return window['go']['main']['App']['GetSessionTimeline']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasActiveWork() {
  return window['go']['main']['App']['HasActiveWork']();
}

export function ListJavaProcesses(arg1) {
  return window['go']['main']['App']['ListJavaProcesses'](arg1);
}

export function LoadQuickCommands() {
  return window['go']['main']['App']['LoadQuickCommands']();
}

export function ParseIntent(arg1) {
  return window['go']['main']['App']['ParseIntent'](arg1);
}

export function PolishRootCause(arg1) {
  return window['go']['main']['App']['PolishRootCause'](arg1);
}

export function RenameSavedSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSavedSession'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveQuickCommands(arg1) {
  return window['go']['main']['App']['SaveQuickCommands'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopSession(arg1, arg2) {
  return window['go']['main']['App']['StopSession'](arg1, arg2);
}

export function UpdateSessionTimeline(arg1) {
  return window['go']['main']['App']['UpdateSessionTimeline'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['main']['App']['Write'](arg1, arg2);
}
