// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {session_recorder} from '../models';
import {config} from '../models';

export function AskAI(arg1:string):Promise<string>;

export function Broadcast(arg1:Array<string>,arg2:string):Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function Connect(arg1:main.ConnectConfig):Promise<main.ConnectResult>;

export function GenerateConclusionWithContext(arg1:string,arg2:string):Promise<string>;

export function GetSessionTimeline():Promise<session_recorder.TroubleshootingSession>;

export function GetSettings():Promise<config.AppConfig>;

export function ParseIntent(arg1:string):Promise<Array<main.ConnectConfig>>;

export function PolishRootCause(arg1:string):Promise<string>;

export function SaveSettings(arg1:config.AppConfig):Promise<string>;

export function StartSession(arg1:string):Promise<string>;

export function StopSession(arg1:string):Promise<string>;

export function UpdateSessionTimeline(arg1:Array<session_recorder.TimelineEvent>):Promise<string>;

export function Write(arg1:string,arg2:string):Promise<void>;
