// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function AskTroubleshoot(arg1, arg2) {
  return window['go']['main']['App']['AskTroubleshoot'](arg1, arg2);
}

export function Broadcast(arg1, arg2) {
  return window['go']['main']['App']['Broadcast'](arg1, arg2);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteSavedSession(arg1) {
  return window['go']['main']['App']['DeleteSavedSession'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function DuplicateSession(arg1) {
  return window['go']['main']['App']['DuplicateSession'](arg1);
}

export function ExportScript(arg1) {
  return window['go']['main']['App']['ExportScript'](arg1);
}

export function FTCancel(arg1) {
  return window['go']['main']['App']['FTCancel'](arg1);
}

export function FTCheck(arg1) {
  return window['go']['main']['App']['FTCheck'](arg1);
}

export function FTDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['FTDownload'](arg1, arg2, arg3);
}

export function FTList(arg1, arg2) {
  return window['go']['main']['App']['FTList'](arg1, arg2);
}

export function FTRemoteMkdir(arg1, arg2) {
  return window['go']['main']['App']['FTRemoteMkdir'](arg1, arg2);
}

export function FTRemoteReadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['FTRemoteReadFile'](arg1, arg2, arg3);
}

export function FTRemoteRemove(arg1, arg2) {
  return window['go']['main']['App']['FTRemoteRemove'](arg1, arg2);
}

export function FTRemoteRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['FTRemoteRename'](arg1, arg2, arg3);
}

export function FTRemoteWriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['FTRemoteWriteFile'](arg1, arg2, arg3);
}

export function FTStat(arg1, arg2) {
  return window['go']['main']['App']['FTStat'](arg1, arg2);
}

export function FTUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['FTUpload'](arg1, arg2, arg3);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GenerateConclusionWithContext(arg1, arg2) {
  return window['go']['main']['App']['GenerateConclusionWithContext'](arg1, arg2);
}

export function GenerateLinuxCommand(arg1) {
  return window['go']['main']['App']['GenerateLinuxCommand'](arg1);
}

export function GetCompletions(arg1, arg2) {
  return window['go']['main']['App']['GetCompletions'](arg1, arg2);
}

export function GetHighlightRules() {
  return window['go']['main']['App']['GetHighlightRules']();
}

export function GetQuickCommandGroups() {
  return window['go']['main']['App']['GetQuickCommandGroups']();
}

export function GetSavedSessions() {
  return window['go']['main']['App']['GetSavedSessions']();
}

export function GetScriptList() {
  return window['go']['main']['App']['GetScriptList']();
}

export function GetScriptRecordingStatus() {
  return window['go']['main']['App']['GetScriptRecordingStatus']();
}

export function GetSessionTimeline() {
  return window['go']['main']['App']['GetSessionTimeline']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasActiveWork() {
  return window['go']['main']['App']['HasActiveWork']();
}

export function ImportConfigFromDirectory(arg1) {
  return window['go']['main']['App']['ImportConfigFromDirectory'](arg1);
}

export function LoadQuickCommands() {
  return window['go']['main']['App']['LoadQuickCommands']();
}

export function LoadScript(arg1) {
  return window['go']['main']['App']['LoadScript'](arg1);
}

export function LocalList(arg1) {
  return window['go']['main']['App']['LocalList'](arg1);
}

export function LocalMkdir(arg1) {
  return window['go']['main']['App']['LocalMkdir'](arg1);
}

export function LocalRemove(arg1) {
  return window['go']['main']['App']['LocalRemove'](arg1);
}

export function LocalRename(arg1, arg2) {
  return window['go']['main']['App']['LocalRename'](arg1, arg2);
}

export function LocalStat(arg1) {
  return window['go']['main']['App']['LocalStat'](arg1);
}

export function ParseIntent(arg1) {
  return window['go']['main']['App']['ParseIntent'](arg1);
}

export function PolishRootCause(arg1) {
  return window['go']['main']['App']['PolishRootCause'](arg1);
}

export function ReconnectSession(arg1) {
  return window['go']['main']['App']['ReconnectSession'](arg1);
}

export function RenameSavedSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSavedSession'](arg1, arg2);
}

export function ReplayScript(arg1, arg2) {
  return window['go']['main']['App']['ReplayScript'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveHighlightRules(arg1) {
  return window['go']['main']['App']['SaveHighlightRules'](arg1);
}

export function SaveQuickCommands(arg1) {
  return window['go']['main']['App']['SaveQuickCommands'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function StartScriptRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartScriptRecording'](arg1, arg2, arg3);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopScriptRecording() {
  return window['go']['main']['App']['StopScriptRecording']();
}

export function StopSession(arg1, arg2) {
  return window['go']['main']['App']['StopSession'](arg1, arg2);
}

export function UpdateSavedSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateSavedSession'](arg1, arg2);
}

export function UpdateScript(arg1) {
  return window['go']['main']['App']['UpdateScript'](arg1);
}

export function UpdateSessionTimeline(arg1) {
  return window['go']['main']['App']['UpdateSessionTimeline'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['main']['App']['Write'](arg1, arg2);
}
