// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Broadcast(arg1, arg2) {
  return window['go']['main']['App']['Broadcast'](arg1, arg2);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ParseIntent(arg1) {
  return window['go']['main']['App']['ParseIntent'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['main']['App']['Write'](arg1, arg2);
}
